Streamlined

diff --git a/makeca b/makeca
--- a/makeca
+++ b/makeca
@@ -3,15 +3,11 @@
 EMAIL="$(whoami)@local.dev"
 
 main() {
-	usage="Usage:$0 store_dir dname"
+	usage="Usage:$0 store_dir"
 	store=$1
-	dname=$2
 	[[ $store ]] || { err $usage; return 2; }
-	[[ $dname ]] || { err $usage; return 2; }
 	[ -d $store ] && { err "Directory $store already exist; aborting"; return 2; }
 	[ -f $store ] && { err "File $store already exist; aborting"; return 2; }
-	_parse_dname $dname
-	DIR_CN="root"
 	mkdir -p $store || return 3
 	cd $store || return 3
 	touch ca || return 3
@@ -30,20 +26,11 @@ main() {
 	# Extract Public Key
 	openssl rsa -passin file:passphrase -in ca.pem -pubout > ca_pub.pem || return 3
 	# Generate root certificate
+	local subject="/CN=\${DIR_CN}/OU=\${DIR_OU}/O=\${DIR_O}/ST=\${DIR_ST}/C=\${DIR_C}"
 	openssl req -passin file:passphrase -x509 -new -nodes -key ca.pem -sha256 -days 36500 -out ca.crt -config ca.cnf || return 3
 	err "Store $store created"
-}
 
-_parse_dname() {
-	for i in ${1//,/ }; do
-		key=$(echo $i | cut -d'=' -f1)
-		value=$(echo $i | cut -d'=' -f2)
-		[[ "$key" == "CN" ]] && DIR_CN=$value
-		[[ "$key" == "OU" ]] && DIR_OU=$value
-		[[ "$key" == "O" ]] && DIR_O=$value
-		[[ "$key" == "ST" ]] && DIR_ST=$value
-		[[ "$key" == "C" ]] && DIR_C=$value
-	done
+	# openssl x509 -subject -noout -in store/ca.crt
 }
 
 echo_ca_cnf() {
@@ -109,22 +96,22 @@ echo_ca_cnf() {
 
 	[ req_distinguished_name ]
 	countryName			= Country Name (2 letter code)
-	countryName_default		= $DIR_C
+	countryName_default		= US
 	countryName_min			= 2
 	countryName_max			= 2
 
 	stateOrProvinceName		= State or Province Name (full name)
-	stateOrProvinceName_default	= $DIR_ST
+	stateOrProvinceName_default	= TX
 
 	0.organizationName		= Organization Name (eg, company)
-	0.organizationName_default	= $DIR_O
+	0.organizationName_default	= TechBros
 
 	organizationalUnitName		= Organizational Unit Name (eg, section)
-	organizationalUnitName_default	= $DIR_OU
+	organizationalUnitName_default	= Widgets
 
 	commonName			= Common Name (e.g. server FQDN or YOUR name)
 	commonName_max			= 64
-	commonName_default = $DIR_CN
+	commonName_default = root
 
 	emailAddress			= Email Address
 	emailAddress_max		= 64
@@ -199,51 +186,69 @@ echo_signcert() {
 }
 
 echo_makecert(){
-cat <<EOF
-#!/bin/bash
+	cat <<-EOF
+	#!/bin/bash
 
-main() {
-	which openssl > /dev/null 2>&1 || { err "Unable to find openssl in path"; return 2; }
-	local name=\$1
-	local dname=\$2
-	local pass=\$3
-	local output_dir=\$4
-	pushd \$(dirname \$0) > /dev/null 2>&2
-	ca=\$PWD
-	popd > /dev/null 2>&1
-	local usage="Usage \$0 name dname pass output_dir"
-	[[ \$name ]] || { err \$usage; return 2; }
-	[[ \$dname ]] || { err \$usage; return 2; }
-	[[ \$pass ]] || { err \$usage; return 2; }
-	[[ \$output_dir ]] || { err \$usage; return 2; }
-	[ -d \$output_dir ] || mkdir -p \$output_dir
-	cd \$output_dir
-	[ -f \${ca}/certs/\${name}.crt ] && { err "Cert with name \$name already exist"; return 2; }
-	[ -d \$name ] && { err "Directory with name \$name already exist"; return 2; }
-	mkdir \$name || { err "Unable to create directory \$name"; return 2; }
-	cd \$name 
-	cp \${ca}/ca.crt . || { err "Unable to copy file \${ca}/ca.crt"; return 2; }
-	openssl genrsa -out key 2048 || { err "Unable to generate key"; return 2; }
-	local subject="/CN=\${name}/\${dname}"
-	openssl req -new -key key -out csr -subj \$subject -passin pass:\${pass} ||
-		{ err "Unable to create request"; return 2; }
-	mv csr \${ca}/sign_request/\${name}.csr ||
-		{ err "Unable to move csr to \${ca}/sign_request"; return 2; }
-	\${ca}/signcert || { err "Unable so sign request"; return 2; }
-	cp \${ca}/certs/\${name}.crt crt ||
-		{ err "Unable to copy file \${ca}/certs/\${name}.crt"; return 2; }
-	openssl pkcs12 -export -in crt -inkey key -name \${name} -out p12 -passout pass:\${pass}
-	which keytool > /dev/null 2>&1 || { err "keytool not found, keystore will not be created"; return 0; }
-	keytool -import  -noprompt -storepass \$pass -keystore keystore -alias root -trustcacerts -file ca.crt ||
-		{ err "keystore creation/importation of ca.crt failed"; return 2; }
-	keytool -importkeystore -deststorepass \$pass -destkeystore keystore -srckeystore p12 -srcstorepass \$pass -srcstoretype PKCS12 ||
-		{ err "keystore importation of pkcs12 failed"; return 2; }
-}
+	main() {
+	  which openssl > /dev/null 2>&1 || { err "Unable to find openssl in path"; return 2; }
+	  local dname=\$1
+	  local pass=\$2
+	  local output_dir=\$3
 
-err() { echo "\$@" 1>&2; }
-main \$@
+	  pushd \$(dirname \$0) > /dev/null 2>&2
+	  ca=\$PWD
+	  popd > /dev/null 2>&1
+	  local usage="Usage \$0 dname pass output_dir"
+	  [[ \$dname ]] || { err \$usage; return 2; }
+	  _parse_dname \$(openssl x509 -subject -noout -in \${ca}/ca.crt)
+	  unset DIR_CN
+	  _parse_dname \$dname
+	  [[ \$DIR_CN ]] || { err "CN=name is required"; return 2; }
+	  [[ \$pass ]] || { err \$usage; return 2; }
+	  [[ \$output_dir ]] || { err \$usage; return 2; }
+	  [ -d \$output_dir ] || mkdir -p \$output_dir
+	  cd \$output_dir
+	  [ -f \${ca}/certs/\${DIR_CN}.crt ] && { err "Cert with name \$DIR_CN already exist"; return 2; }
+	  [ -d \$DIR_CN ] && { err "Directory with $\DIR_CN \$DIR_CN already exist"; return 2; }
+	  mkdir \$DIR_CN || { err "Unable to create directory \$DIR_CN"; return 2; }
+	  cd \$DIR_CN 
+	  cp \${ca}/ca.crt . || { err "Unable to copy file \${ca}/ca.crt"; return 2; }
+	  openssl genrsa -out key 2048 || { err "Unable to generate key"; return 2; }
+	  local subject="/CN=\${DIR_CN}/OU=\${DIR_OU}/O=\${DIR_O}/ST=\${DIR_ST}/C=\${DIR_C}"
+	  openssl req -new -key key -out csr -subj \$subject -passin pass:\${pass} || { err "Unable to create request"; return 2; }
+	  mv csr \${ca}/sign_request/\${DIR_CN}.csr || { err "Unable to move csr to \${ca}/sign_request"; return 2; }
+	  \${ca}/signcert || { err "Unable so sign request"; return 2; }
+	  cp \${ca}/certs/\${DIR_CN}.crt crt || { err "Unable to copy file \${ca}/certs/\${DIR_CN}.crt"; return 2; }
+	  openssl pkcs12 -export -in crt -inkey key -out p12 -passout pass:\${pass}
+	  which keytool > /dev/null 2>&1 || { err "keytool not found, keystore will not be created"; return 0; }
+	  keytool -import  -noprompt -storepass \$pass -keystore keystore -alias root -trustcacerts -file ca.crt ||
+	    { err "keystore creation/importation of ca.crt failed"; return 2; }
+	  keytool -importkeystore -deststorepass \$pass -destkeystore keystore -srckeystore p12 -srcstorepass \$pass -srcstoretype PKCS12 ||
+	    { err "keystore importation of pkcs12 failed"; return 2; }
+	}
 
-EOF
+	_parse_dname() {
+	  _parse() {
+	    key=\$(echo \$i | cut -d'=' -f1 | tr '[:lower:]' '[:upper:]')
+	    value=\$(echo \$i | cut -d'=' -f2)
+	    [[ "\$key" == "CN" ]] && DIR_CN=\$value
+	    [[ "\$key" == "cn" ]] && DIR_CN=\$value
+	    [[ "\$key" == "OU" ]] && DIR_OU=\$value
+	    [[ "\$key" == "O" ]] && DIR_O=\$value
+	    [[ "\$key" == "ST" ]] && DIR_ST=\$value
+	    [[ "\$key" == "C" ]] && DIR_C=\$value
+	  }
+	  for i in \${@//\// }; do
+	    _parse
+	  done
+	  for i in \${@//,/ }; do
+	    _parse
+	  done
+	}
+
+	err() { echo "\$@" 1>&2; }
+	main \$@
+	EOF
 }
 
 err() { echo "$@" 1>&2; }
